### ISSUE TITLE
Getting error while calculating the capgains

### ISSUE THREAD

**Issue by archana-2** [EmilMaric/cad-capital-gains#27]
I try to calculate the capgains but getting error.

Sample file:
2017-2-15,ESPP PURCHASE,GOOG,BUY,100,50.00,10.00,USD
2017-5-20,RSU VEST,GOOG,SELL,50,45.00,0.00,CAD

Command:
capgains calc sample_1.csv 2017

Error:
Error: Error with internet connection to URL https://www.bankofcanada.ca/valet/observations/FXUSDCAD/json : HTTPSConnectionPool(host='www.bankofcanada.ca', port=443): Max retries exceeded with url: /valet/observations/FXUSDCAD/json?start_date=2017-02-08&end_date=2017-02-15 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f75d2c8fdd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Python version using:
Python 3.6.9

**Comment by archana-2** [comment]
Hello,

I'll again check it out. If it doesn't work then I'll let you know.

Thanks for your help,
Archana

**Comment by EmilMaric** [comment]
Hey @archana-2 

As promised, I tried running this tonight with python 3.6.9 and could not reproduce the error you're seeing. Here is what I saw:
```
❯ capgains calc test.csv 2017
GOOG-2017
[Total Gains = -1,028.54]
+------------+---------------+----------+-------+------------+----------+-----------+---------------------+
| date       | description   | ticker   | qty   |   proceeds |      ACB |   outlays |   capital gain/loss |
|------------+---------------+----------+-------+------------+----------+-----------+---------------------|
| 2017-05-20 | RSU VEST      | GOOG     | 50    |   2,250.00 | 3,278.54 |      0.00 |           -1,028.54 |
+------------+---------------+----------+-------+------------+----------+-----------+---------------------+
```

As mentioned in my earlier comment, I believe there may have been a problem with your internet connection or perhaps firewall settings at the time. Can you try pasting the following URL in your browser and see if you get a JSON file to download: https://www.bankofcanada.ca/valet/observations/FXUSDCAD/json?start_date=2017-02-08&end_date=2017-02-15

**Comment by archana-2** [comment]
Hello,

Ya I think because of network issue i get that error. I'll try and close
this issue.

Thank you for your help.
Archana
