### ISSUE TITLE
Pip version 2.0.1 Doesn

### ISSUE THREAD

**Issue by mohitnihalani** [EmilMaric/cad-capital-gains#32]

**Comment by mohitnihalani** [comment]
Can you release the latest version, which supports fractional shares, as the version currently on pip doesn't support it.

**Comment by EmilMaric** [comment]
Hi @mohitnihalani, the latest version (2.0.1) should support fractional shares. If you are seeing errors with fractional shares can you please include some more info about what your transactions CSV file looks like.

**Comment by AC0DEM0NK3Y** [comment]
> Hi @mohitnihalani, the latest version (2.0.1) should support fractional shares. If you are seeing errors with fractional shares can you please include some more info about what your transactions CSV file looks like.

You can find more info in #33

**Comment by EmilMaric** [comment]
@mohitnihalani Apologies for my original mistake, v2.0.1 did not have support for partial shares.

I've pushed a new release 2.0.2 that should now support partial shares. Please let me know if you encounter any issues.
