### ISSUE TITLE
Sum up each tickers total capital gains at the bottom of each table

### ISSUE THREAD

**Issue by EmilMaric** [EmilMaric/cad-capital-gains#8]
We should show the total capital gains owed at the bottom of the table for each ticker.

**Comment by EddyMaric** [comment]
I think its better if we have it at the top, underneath the TICKER-YEAR

So if you're only interested in the gains for that ticker for that year, you can quickly correlate the 3 values without having to look for it at the bottom of the table.

Imagine if you had 10 different tickers and each one had 100 entries. You might scroll down and forget what ticker you were looking for. But if it was right next to the name and year, you would know right away.
